// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/apps/v1"
)

// InterfaceK8s is an autogenerated mock type for the InterfaceK8s type
type InterfaceK8s struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, d
func (_m *InterfaceK8s) Create(ctx context.Context, d *v1.Deployment) error {
	ret := _m.Called(ctx, d)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Deployment) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
