basePath: /api/v1
definitions:
  models.CreateClusterReq:
    properties:
      name:
        type: string
    type: object
  models.CreateClusterRes:
    properties:
      response:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /cluster:
    post:
      consumes:
      - application/json
      description: This is the description
      parameters:
      - description: create cluster req
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.CreateClusterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateClusterRes'
      summary: Create a  cluster
      tags:
      - cluster
swagger: "2.0"
